### ISSUE TITLE
AnchorConnectionProvider throws an error related with Buffer

### ISSUE THREAD

**Issue by silvestrevivo** [svelte-on-solana/wallet-adapter#15]
**Describe the bug**
When running `npn run dev`, the AnchorConnectionProvider is throwing an error related with Buffer package.

```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/buffer/index.js?v=8e2ae606' does not provide an export named 'Buffer'
```

**To Reproduce**
1. `npn run dev`
2. Open console
3. See error

**Expected behavior**
This shouldn't be happening since Buffer workaround is described in the docs.

**Comment by cogoo** [comment]
fixed in #17
