### ISSUE TITLE
Update UI package with latest styles

### ISSUE THREAD

**Issue by cogoo** [svelte-on-solana/wallet-adapter#19]
Styles for the wallet adapter UI have been updated screenshot attached

Additional features

- [ ] show detected wallets

![wallets](https://user-images.githubusercontent.com/14809642/156996438-1d2eedc9-aa20-4ee0-a641-2ac3cad3962d.png)

**Comment by alvinsga** [comment]
Is there the ability to customise styles, especially on the connect button?

**Comment by silvestrevivo** [comment]
@alvinsga you can always customise the style using the `:global()` directive targeting the classes, but that is a lot of work. We were thinking that it would be a great idea to find a way to make possible that, but we have to discuss still the way to do it. If you have an idea please, new issues and PR's are welcome.

**Comment by kylebuildsstuff** [comment]
> @alvinsga you can always customise the style using the `:global()` directive targeting the classes, but that is a lot of work. We were thinking that it would be a great idea to find a way to make possible that, but we have to discuss still the way to do it. If you have an idea please, new issues and PR's are welcome.

Just tossing some ideas, but what if you could pass in some external classes to override the existing classes? 

The `WalletMultiAdapter` seems to only have about 5 or so classes so it seems like it'd be a good fit to enable popular CSS practices like utility classes. Example of the API would look something like in here: https://github.com/flekschas/svelte-simple-modal#styling
