### ISSUE TITLE
Wallet webpage not opening if wallet is not installed

### ISSUE THREAD

**Issue by alvinsga** [svelte-on-solana/wallet-adapter#20]
**Describe the bug**
If user does not have the wallet installed on their browser, they should be redirected to the wallet webpage to download the wallet. This is currently not happening. 

**To Reproduce**
1. Disable all wallet extensions
2. Go to https://solana-svelte-counter.netlify.app/ 
3. Select connect wallet and click one.
4. Dialog box closes without redirecting user to download wallet

**Expected behavior**
User should be redirected to the wallet webpage to download the wallet

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: tested on Chrome and Brave
 - Version: 99

**Comment by silvestrevivo** [comment]
@alvinsga thanks for opening this issue. We will check it out.

**Comment by silvestrevivo** [comment]
@alvinsga thanks for opening this issue. We will check it out.
