### ISSUE TITLE
Adapter breaking using ConnectionProvider, issue with some docs

### ISSUE THREAD

**Issue by silvestrevivo** [svelte-on-solana/wallet-adapter#23]
**Describe the bug**

When the ConnectionProvider is used, the Solana web3 library breaks. It seems not to be solving correctly some node-built packages, especially the `buffer-layout`. 

The documentation is not correctly. In the UI package, the npm page has a snippet to install the package that is not correct. 

https://www.npmjs.com/package/@svelte-on-solana/wallet-adapter-ui (`npm i @svelte-on-solana/wallet-adapter-svelte-ui`)

The instruction about the `svelte.config.js` file, is missing the vite property and it not so clear where to place the `define` property. We need to include `vite` like in the Anchor package. 

```
const config = {
	preprocess: preprocess(),

	kit: {
		 vite: {
		      define: {
			'process.env.BROWSER': true
		     }
	       }
	}
};
```

**To Reproduce**
Steps to reproduce the issue with the ConnectionProvider:
1. Init a empty repo with the last SvelteKit version
2. Install the last version of all the packages from Solana Labs, includes Solana Web3
3. Don't install Anchor. This is an issue related with the adapter implementation with just Solana
4. Follow the instructions to implement the wallet
5. Run the project and see the error on console

**Solution**
A proposal that I've tested and it is working (tested by another 3 persons on different computers and devices) is to remove the ConnectionProvider and replace it for the ContextAPI. 

```
<script lang="ts">
	import { onMount, setContext } from 'svelte';
	import { WalletProvider, WalletMultiButton } from '@svelte-on-solana/wallet-adapter-ui';
	import { Connection } from '@solana/web3.js';

	const network = 'http://127.0.0.1:8899';
	const localStorageKey = 'walletAdapter';
	const connection = new Connection(network, 'processed');
	setContext<Connection>('connection', connection);

	let wallets;
	onMount(async () => {
		const { PhantomWalletAdapter, SolflareWalletAdapter } = await import(
			'@solana/wallet-adapter-wallets'
		);
		wallets = [new PhantomWalletAdapter(), new SolflareWalletAdapter()];
	});
</script>

<WalletProvider {localStorageKey} {wallets} autoConnect />
<main>
	<slot />
</main>
<WalletMultiButton />
```

Since `__layout.svelte` is the root component in the application, we can call the getContext() function to bring the connection. This data doesn't need to be reactive, thus is possible to share it with Context API as inmutable content. 

**Additional context**
Another possible solution could be to add eventemmiter3 to the UI library and avoid so many refactor in the implementation and the docs. This is something to be tested.

**Comment by cogoo** [comment]
Could you add the console error you get as part of the issue please

**Comment by cogoo** [comment]
I think whats required for this is to add `@solana/web3.js` in optimize deps:

```
optimizeDeps: {
  include: ['@solana/web3.js', '@solana/pay']
},
```

I think its to do with ESM compatibility. See vite docs: https://vitejs.dev/guide/dep-pre-bundling.html#dependency-pre-bundling

**Comment by silvestrevivo** [comment]
@cogoo that's is the solution. Maybe we need to include that on the docs to prevent someone else gets the same error.

**Comment by CeNiEi** [comment]
I recently ran into this error while using Anchor.
Although the given solution works, it seems that the docs are not updated for Anchor users. 
https://github.com/svelte-on-solana/wallet-adapter/blob/master/packages/anchor/README.md

In `svelte.config.js` we also need to include `@solana/web3.js` in `optimzeDeps`.

**Comment by silvestrevivo** [comment]
@CeNiEi I think that partially you are right. In the UI package is mentioned all this stuff, even I have added in the last update the `buffer` package inside the `optimzeDeps` because as soon as you start to work with minting, the app is gonna fail. 

What I mean with this is that you don't need to add this dependencies in `optimzeDeps` to start to work with Anchor, but as some point you will need them. Maybe it would be a good idea to include some notes in the Anchor docs about this.
