### ISSUE TITLE
svelte-on-solana/wallet-adapter-anchor keep throwing TypeError: Cannot read properties of undefined (reading 'BROWSER')

### ISSUE THREAD

**Issue by Abdulkereem** [svelte-on-solana/wallet-adapter#24]
i am using svelte solana wallet adapter, when i tried to use workSpace from @svelte-on-solana/wallet-adapter-anchor
i keep getting error TypeError: Cannot read properties of undefined (reading 'BROWSER')

**To Reproduce**
import workSpace from @svelte-on-solana/wallet-adapter-anchor in sveltekit 
see below from my svelte.config.js

`import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';
import path from 'path';

const config = {
  preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		vite: {
      optimizeDeps: {
        include: ['@project-serum/anchor'],
      },
      resolve: {
        alias: {
          $utils: path.resolve('src/utils/'),
        },
      },
      define: {
        // This makes @project-serum/anchor 's process error not happen since it replaces all instances of process.env.BROWSER with true
        'process.env.BROWSER': true
      },
    },
  },
};

export default config;
`

i want to use workSpace to gain access to base account and sign transactions

 - OS: MacOs Monterey
 - Browser chrome,
 - Sveltkit version: next

**Comment by silvestrevivo** [comment]
Hi @Abdulkereem 

I think you have to import the `workSpace` from `import { workSpace } from '@svelte-on-solana/wallet-adapter-ui';`

Let me know please if that is the issue. Thanks!!!

**Comment by Abdulkereem** [comment]
> 

thanks for the swift response @silvestrevivo  i have tried that but i couldn't access $workSpace.baseAccount it keep throwing undefine

**Comment by Abdulkereem** [comment]
after downgrading to https://github.com/silvestrevivo/solana-svelte-counter package.json ,     "@svelte-on-solana/wallet-adapter-anchor": "^1.0.11-alpha.0",
the  TypeError: Cannot read properties of undefined (reading 'BROWSER') is cleared, when i tried to access $workSpace.baseaccount it throw type error undefined

**Comment by Abdulkereem** [comment]
> after downgrading to https://github.com/silvestrevivo/solana-svelte-counter package.json , "@svelte-on-solana/wallet-adapter-anchor": "^1.0.11-alpha.0", the TypeError: Cannot read properties of undefined (reading 'BROWSER') is cleared, when i tried to access $workSpace.baseaccount it throw type error undefined

please any way out, please

**Comment by silvestrevivo** [comment]
@Abdulkereem please, can you provide a repo? It seems you are not initializing the workSpace.

**Comment by Abdulkereem** [comment]
> @Abdulkereem please, can you provide a repo? It seems you are not initializing the workSpace.

okay thanks, here https://github.com/Abdulkereem/therepublik/blob/frontend-production/src/routes/stake/index.svelte

**Comment by Abdulkereem** [comment]
the transaction is where am calling workspace

**Comment by Abdulkereem** [comment]
okay thanks so much, how do, i call it is it in place of ConnectionProvider from @svelte-on-solana/wallet-adapter-ui ?

please i need a guide if there is any kindly share me

**Comment by silvestrevivo** [comment]
https://github.com/svelte-on-solana/wallet-adapter/blob/master/packages/anchor/README.md

**Comment by Abdulkereem** [comment]
okay thanks, that's great please what is the 	import idl from '../../../target/idl/<my-anchor-project>.json'; ?

**Comment by silvestrevivo** [comment]
That's the IDL generated by Anchor build.
