### ISSUE TITLE
Customize maxNumberOfWallets with WalletMultiButton

### ISSUE THREAD

**Issue by andrewjmeier** [svelte-on-solana/wallet-adapter#26]
**Is your feature request related to a problem? Please describe.**
WalletModal has a maxNumberOfWallets prop, but if you use WalletMultiButton to render it, WalletMultiButton does not expose the prop. 

**Describe the solution you'd like**
Add the same prop to WalletMultiButton and pass it through to the modal 

**Describe alternatives you've considered**
I could render the modal directly but that would more or less require rewriting WalletMultiButton myself. 

**Additional context**
I created this change in a branch here: https://github.com/svelte-on-solana/wallet-adapter/compare/master...andrewjmeier:andrew/customize-modal-wallet-count?expand=1 I'd be happy to submit a PR.

**Comment by silvestrevivo** [comment]
Hi @andrewjmeier please, feel free to open a PR to see the changes. Thanks!!

**Comment by andrewjmeier** [comment]
@silvestrevivo done: https://github.com/svelte-on-solana/wallet-adapter/pull/27

**Comment by andrewjmeier** [comment]
@silvestrevivo can we merge?

**Comment by silvestrevivo** [comment]
@andrewjmeier I left a comment on the PR. Thanks!

**Comment by silvestrevivo** [comment]
Changes published https://www.npmjs.com/package/@svelte-on-solana/wallet-adapter-ui/v/1.0.14-alpha.0
