### ISSUE TITLE
Where do i get the idl json??

### ISSUE THREAD

**Issue by ruskkartel** [svelte-on-solana/wallet-adapter#37]
import idl from '../../../target/idl/<my-anchor-project>.json';

**Comment by silvestrevivo** [comment]
@ruskkartel working with Anchor, the frontend is placed in the folder `App`. When you build in Anchor, this generates a `idl.json` inside the target folder. When you try to import the `idl.json` from the `__layout.svelte` file, that is the route you what have to point to. Does it make sense?

**Comment by silvestrevivo** [comment]
@ruskkartel closing issue since the question seems to be solved.
