### ISSUE TITLE
Wallet Connection / AutoConnect

### ISSUE THREAD

**Issue by tiagoappetite** [svelte-on-solana/wallet-adapter#42]
Followed all the guidelines of setup provided in here.

Did set this up on brand new and fresh SvelteKit installation but the "Connect" to wallet button doesn't seem to work properly. 

1 - You click "Select Wallet"
2 - It changes the button to "Connect" which you must click on
3 - Always you refresh the page the connection is lost and you need to click on "Connect" again

I've tried this on regular Svelte (non-SvelteKit) and same issue happens.

My understanding is this is being caused somehow by latest libraries / projects on Vite 3+

**Comment by gaylonalfano** [comment]
I'm getting similar behavior @tiagoappetite. Did you happen to get this resolved?

**Comment by tiagoappetite** [comment]
> I'm getting similar behavior @tiagoappetite. Did you happen to get this resolved?

SvelteKit just got updated last night and it solves the issue.
Update Svelte and make sure you've those settings on your vite.config.js

```
	plugins: [sveltekit()],
	optimizeDeps: {
		esbuildOptions: {
			target: 'esnext'
		}
	},
	build: {
		target: 'esnext'
	}
```
